version: "3.8"
services:
  apache_php:
    build: ./apache
    restart: always
    volumes:
      - ./src/apache:/var/www/html
    ports:
      - "8080:80"
  db:
    build: ./mariadb
    restart: always
    volumes:
      - ./src/mariadb:/docker-entrypoint-initdb.d