version: "3.8"
services:
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./nginx/src:/etc/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  apache-php:
    build: ./apache-php
    restart: always
    volumes:
      - ./apache-php/src:/var/www/html
      - ./apache-php/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache-php/php.ini:/usr/local/etc/php/conf.d/php.ini
  mysql:
    platform: linux/x86_64
    build: ./mysql
    restart: always
    volumes:
      - ./mysql/src:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  redis:
    build: ./redis
    restart: always
    ports:
      - "6379:6379"
  mongodb:
    build: ./mongodb
    restart: always
    ports:
      - "27017:27017"
