version: "3.8"
services:
  nginx:
    build: nginx
    restart: always
    volumes:
      - ./nginx/src:/var/www/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "8080:8080"
  apache-php:
    build: ./apache-php
    restart: always
    volumes:
      - ./apache-php/src:/var/www/dynamic
#  db:
#    build: ./mariadb
##    restart: always
#    volumes:
#      - ./mariadb/src:/docker-entrypoint-initdb.d